spring:
  application:
    name: zuul-server

server:
  port: 8090
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    productos:
      service-id: farmcli-service-product
      path: /api/products/**
    items:
      service-id: farmcli-service-items
      path: /api/items/**
    users:
      service-id: farmcli-service-users
      path: /api/usr/**
    security:
      service-id: farmcli-service-oauth
      path: /api/security/**
      sensitive-headers:
      - Cookie
      - Set-Cookie
      
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 200000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000