spring:
  application:
    name: farmcli-service-items
server:
  port: 8002

#farmcli-service-product:
#  ribbon:
#    listOfServers: localhost:8001,localhost:9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 200000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000