
spring:
  application:
    name: farmcli-service-product
    
server:
  port: ${PORT:0}
#  servlet:
#    context-path: /farmcli-service-product/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}